- name: "Proxmox: Clone VM and set VM resources"
  connection: local
  hosts: all
  gather_facts: False

  vars:
    collected_proxmox_vm: {}
    collected_proxmox_lxc: {}

  tasks:
  - name: Include Proxmox VM discovery
    include_tasks: "ansible-tasks/collect-proxmox-vm.yml"

  - name: Include Proxmox LXC discovery
    include_tasks: "ansible-tasks/collect-proxmox-lxc.yml"

  - name: SHOW US vmconfig
    debug:
      msg: "vm_config {{ vm_config }}"

  - name: Show us NetBox config
    debug:
      msg: "NetBox config {{ netbox_env_info }}"

  - name: Show us Proxmox config
    debug:
      msg: "Proxmox config {{ proxmox_env_info }}"

  - name: Show us id of template (integer)
    debug:
      msg: "ID of template (integer) {{ vm_config['template'] | int }}"

  - name: Create VM from a full clone of template
    community.proxmox.proxmox_kvm:
      node: "{{ proxmox_env_info.node }}"
      api_user: "{{ proxmox_env_info.api_user }}"
      api_token_id: "{{ proxmox_env_info.api_token_id }}"
      api_token_secret: "{{ proxmox_env_info.api_token_secret }}"
      api_host: "{{ proxmox_env_info.api_host }}"
      api_port: "{{ proxmox_env_info.api_port }}"
      clone: "{{ vm_config['template'] }}"
      vmid: "{{ vm_config['template'] }}"
      name: "{{ vm_config['name'] }}"
      newid: "{{ vm_config['vmid'] | int | default(omit) }}"
      agent: 'enabled=1'
      storage: "{{ vm_config['storage'] }}"
      #onboot: "{{ vm_config_create[item].auto_start }}"
      state: present
      timeout: 120
    when: not vm_config['name'] in collected_proxmox_vm and not vm_config['name'] in collected_proxmox_lxc
    register: clone_vm_job
    async: 180
    poll: 0

  - name: Wait for VM cloning processes to finish
    async_status:
      jid: "{{ clone_vm_job.ansible_job_id }}"
    register: _jobs_alias_vc_0
    until: _jobs_alias_vc_0.finished
    retries: 60
    delay: 5
    when: not vm_config['name'] in collected_proxmox_vm

  - name: Update Proxmox VMs resource settings
    community.proxmox.proxmox_kvm:
      node: "{{ proxmox_env_info.node }}"
      api_user: "{{ proxmox_env_info.api_user }}"
      api_token_id: "{{ proxmox_env_info.api_token_id }}"
      api_token_secret: "{{ proxmox_env_info.api_token_secret }}"
      api_host: "{{ proxmox_env_info.api_host }}"
      name: "{{ vm_config['name'] }}"
      cores: "{{ vm_config['vcpus'] | int }}"
      vcpus: "{{ vm_config['vcpus'] | int }}"
      memory: "{{ vm_config['memory'] }}"
      update: true
    register: update_vms_settings_job
    async: 180
    poll: 0

  - name: Wait for VM settings updates processes to finish
    async_status:
      jid: "{{ update_vms_settings_job.ansible_job_id }}"
    register: _ujobs_alias_vc_0
    until: _ujobs_alias_vc_0.finished
    retries: 60
    delay: 10

  - name: "Discover information for newly-created Proxmox VM"
    community.proxmox.proxmox_vm_info:
      api_host: "{{ proxmox_env_info.api_host | default(omit) }}"
      api_user: "{{ proxmox_env_info.api_user | default(omit) }}"
      api_token_id: "{{ proxmox_env_info.api_token_id | default(omit) }}"
      api_token_secret: "{{ proxmox_env_info.api_token_secret | default(omit) }}"
      node: "{{ proxmox_env_info.node }}"
      name: "{{ vm_config['name'] }}"
    register: new_proxmox_vm

  - name: Show us new VM info
    debug:
      msg: "New VM info: {{ new_proxmox_vm }}"

  - name: "Update Proxmox vmid for VM in NetBox"
    netbox.netbox.netbox_virtual_machine:
      netbox_url: "{{ netbox_env_info.api_proto }}://{{ netbox_env_info.api_host }}:{{ netbox_env_info.api_port}}"
      netbox_token: "{{ netbox_env_info.api_token }}"
      data:
        name: "{{ new_proxmox_vm.proxmox_vms[0].name }}"
        custom_fields:
          proxmox_vmid: "{{ new_proxmox_vm.proxmox_vms[0].vmid }}"
      state: present
    when: new_proxmox_vm is defined and new_proxmox_vm.proxmox_vms is defined and new_proxmox_vm.proxmox_vms | length > 0 and vm_config['vmid'] is defined and vm_config['vmid'] == "None"

# ok: [localhost] => {
#    "msg": "New VM info: {'changed': False, 'proxmox_vms': [{'maxcpu': 1, 'status': 'stopped', 'netout': 0, 'vmid': 104, 'diskwrite': 0, 'id': 'qemu/104', 'uptime': 0, 'node': 'proxmox-ve', 'disk': 0, 'maxdisk': 2361393152, 'type': 'qemu', 'maxmem': 268435456, 'template': False, 'mem': 0, 'diskread': 0, 'netin': 0, 'cpu': 0, 'name': 'test2', 'cpus': 1, 'serial': 1}], 'failed': False}"
#}
#  - name: Show human-readable disk size from newly-created VM
#    debug:
#      msg: "human readable disk size: {{ new_proxmox_vm.proxmox_vms[0].maxdisk | human_readable(unit='M') }} ||| {{ new_proxmox_vm.proxmox_vms[0].maxdisk | human_readable(unit='M') | regex_replace('\\s+[M][Bb]$', '') | int | string }} ||| {{ new_proxmox_vm.proxmox_vms[0].maxdisk | human_readable(unit='M') | regex_replace('\\s+[M][Bb]$', '') | int | string | type_debug }}"

  - name: "Update Proxmox storage for VM in NetBox"
    netbox.netbox.netbox_virtual_disk:
      netbox_url: "{{ netbox_env_info.api_proto }}://{{ netbox_env_info.api_host }}:{{ netbox_env_info.api_port}}"
      netbox_token: "{{ netbox_env_info.api_token }}"
      data:
        virtual_machine: "{{ new_proxmox_vm.proxmox_vms[0].name }}"
        name: scsi0
        size: "{{ new_proxmox_vm.proxmox_vms[0].maxdisk | human_readable(unit='M') | regex_replace('\\s+[M][Bb]$', '') | int | string }}"
        custom_fields:
          proxmox_disk_storage_volume: "{{ vm_config['storage'] }}"
      state: present
    when: new_proxmox_vm is defined and new_proxmox_vm.proxmox_vms is defined and new_proxmox_vm.proxmox_vms | length > 0
